use sakila;


# 1. List the number of films per category.

SELECT c.name AS category_name,
    COUNT(f.film_id) AS number_of_films
FROM category AS c
INNER JOIN film_category AS fc ON c.category_id = fc.category_id
INNER JOIN film AS f ON fc.film_id = f.film_id
GROUP BY  c.name
ORDER BY number_of_films DESC;

# 2. Retrieve the store ID, city, and country for each store.

SELECT s.store_id, c.city, cy.country
FROM store AS s
INNER JOIN address AS a ON s.address_id = a.address_id
INNER JOIN city AS c ON a.city_id = c.city_id
INNER JOIN country AS cy ON c.country_id = cy.country_id
ORDER BY s.store_id;

# 3. Calculate the total revenue generated by each store in dollars.

SELECT s.store_id,
    SUM(p.amount) AS total_revenue
FROM store AS s
INNER JOIN staff AS st ON s.store_id = st.store_id
INNER JOIN payment AS p ON st.staff_id = p.staff_id
GROUP BY s.store_id
ORDER BY total_revenue ASC;

# 4. Determine the average running time of films for each category.

SELECT c.name AS category_name,
    AVG(f.length) AS average_running_time
FROM category AS c
INNER JOIN film_category AS fc ON c.category_id = fc.category_id
INNER JOIN film AS f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY average_running_time DESC;

# 5. Identify the film categories with the longest average running time.

SELECT c.name AS category_name,
    AVG(f.length) AS average_running_time
FROM category AS c
INNER JOIN film_category AS fc ON c.category_id = fc.category_id
INNER JOIN film AS f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY average_running_time DESC
LIMIT 1;

# 6. Display the top 10 most frequently rented movies in descending order.

SELECT f.title,
    COUNT(r.rental_id) AS rental_count
FROM film AS f
INNER JOIN inventory AS i ON f.film_id = i.film_id
INNER JOIN rental AS r ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

# 7. Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT
    CASE
        WHEN COUNT(i.inventory_id) > 0 THEN 'Available'
        ELSE 'NOT Available'
    END AS availability_status
FROM film AS f
INNER JOIN inventory AS i ON f.film_id = i.film_id
WHERE f.title = 'ACADEMY DINOSAUR' AND i.store_id = 1;

# 8. Provide a list of all distinct film titles, along with their availability status in the inventory

SELECT
    CASE
        WHEN COUNT(i.inventory_id) > 0 THEN 'Available'
        ELSE 'NOT Available'
    END AS availability_status
FROM film AS f
INNER JOIN inventory AS i ON f.film_id = i.film_id
WHERE f.title = 'ACADEMY DINOSAUR' AND i.store_id = 1;
